version: '3.8'

services:
  mongodb:
    image: mongo:${TAG}
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - gangwars-mongodb_data:/data/db
    restart: unless-stopped

volumes:
  gangwars-mongodb_data: