name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        version: [16,18]
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install deps
        run: npm i
      - name: Install pm2
        run: npm i -g pm2
      - name: Lint
        run: npm run lint
      - name: Run server
        run: pm2 start npm -- start
      - name: Wait
        run: sleep 5

      - name: test getAttack
        run: curl --location 'http://localhost:5000/getAttack'

      - name: Stop server
        run: pm2 delete all
      - name: Logs
        run:  cat ~/.pm2/pm2.log
