name: Check
on: [push,pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        version: [16,18]
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install deps
        run: npm i
      - name: Install pm2
        run: npm i -g pm2
      - name: Lint
        run: npm run lint
      - name: Run server
        run: pm2 start npm -- start
      - name: Wait
        run: sleep 5

      - name: test getAttack api
        run: curl --location --request POST 'http:/127.0.0.1:5000/getAttack' --silent -v 2>&1 | grep 'HTTP/1.1 200'
      - name: test defense/total api
        run: curl --location '127.0.0.1:5000/defense/total' --silent -v 2>&1 | grep 'HTTP/1.1 200'
      - name: test attack/total api
        run: curl --location '127.0.0.1:5000/attack/total' --silent -v 2>&1 | grep 'HTTP/1.1 200'
      - name: test attack/total api
        run: curl --location '127.0.0.1:5000/capos' --silent -v 2>&1 | grep 'HTTP/1.1 200'
      - name: test attack/total capos/update
        run: curl --location --request POST '127.0.0.1:5000/capos/update' --silent -v 2>&1 | grep 'HTTP/1.1 200'
      - name: test attack/total capos/delete
        run: curl --location --request POST '127.0.0.1:5000/capos/delete' --silent -v 2>&1 | grep 'HTTP/1.1 200'


      - name: Stop server
        run: pm2 delete all
      - name: Logs
        run:  cat ~/.pm2/pm2.log
