name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16,18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: Install deps
        run: npm i
      - name: Lint
        run: npm run lint
